### ISSUE TITLE
可以交流下吗？

### ISSUE THREAD

**Issue by Soar360** [newlife/wiig#1]
您好，我是以为北京打工的软件开发者。主要语言是 C# ，最近在学 GO ，可以交流下吗？
qq := base64_decode('ODc3MjM1MDE=')
冒昧打扰，请见谅。

**Comment by newlife** [comment]
你是看我名字好玩才找的我么。。。。

**Comment by Soar360** [comment]
老实说，就是看上你的名字了，可好假转让？详细私聊。
